---
abstract: 'Catalyst Template::Declare View Class'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-TD
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7
  Class::Accessor: 0
  File::Find: 0
  MRO::Compat: 0
  Template::Declare: 0.42
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-TD/trunk
version: 0.12
